; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:AT90CAN128]
platform = atmelavr
board = AT90CAN128
framework = arduino

upload_protocol = arduino
upload_port = /dev/tty.usbserial-A10LJ5RJ
upload_speed = 115200

build_flags = -I$PROJECT_DIR/AST_CAN_Arduino_Library-master/src
